// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SearchEngine.proto

package SearchEngineServerRPC;

public final class SearchEngine {
  private SearchEngine() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface URLRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:URLRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string Keyword = 1;</code>
     */
    java.lang.String getKeyword();
    /**
     * <code>string Keyword = 1;</code>
     */
    com.google.protobuf.ByteString
        getKeywordBytes();
  }
  /**
   * Protobuf type {@code URLRequest}
   */
  public  static final class URLRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:URLRequest)
      URLRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use URLRequest.newBuilder() to construct.
    private URLRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private URLRequest() {
      keyword_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private URLRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              keyword_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SearchEngineServerRPC.SearchEngine.internal_static_URLRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SearchEngineServerRPC.SearchEngine.internal_static_URLRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SearchEngineServerRPC.SearchEngine.URLRequest.class, SearchEngineServerRPC.SearchEngine.URLRequest.Builder.class);
    }

    public static final int KEYWORD_FIELD_NUMBER = 1;
    private volatile java.lang.Object keyword_;
    /**
     * <code>string Keyword = 1;</code>
     */
    public java.lang.String getKeyword() {
      java.lang.Object ref = keyword_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        keyword_ = s;
        return s;
      }
    }
    /**
     * <code>string Keyword = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKeywordBytes() {
      java.lang.Object ref = keyword_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        keyword_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getKeywordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, keyword_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getKeywordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, keyword_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SearchEngineServerRPC.SearchEngine.URLRequest)) {
        return super.equals(obj);
      }
      SearchEngineServerRPC.SearchEngine.URLRequest other = (SearchEngineServerRPC.SearchEngine.URLRequest) obj;

      boolean result = true;
      result = result && getKeyword()
          .equals(other.getKeyword());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + KEYWORD_FIELD_NUMBER;
      hash = (53 * hash) + getKeyword().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SearchEngineServerRPC.SearchEngine.URLRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SearchEngineServerRPC.SearchEngine.URLRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SearchEngineServerRPC.SearchEngine.URLRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SearchEngineServerRPC.SearchEngine.URLRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SearchEngineServerRPC.SearchEngine.URLRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SearchEngineServerRPC.SearchEngine.URLRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SearchEngineServerRPC.SearchEngine.URLRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SearchEngineServerRPC.SearchEngine.URLRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SearchEngineServerRPC.SearchEngine.URLRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SearchEngineServerRPC.SearchEngine.URLRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SearchEngineServerRPC.SearchEngine.URLRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SearchEngineServerRPC.SearchEngine.URLRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SearchEngineServerRPC.SearchEngine.URLRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code URLRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:URLRequest)
        SearchEngineServerRPC.SearchEngine.URLRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SearchEngineServerRPC.SearchEngine.internal_static_URLRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SearchEngineServerRPC.SearchEngine.internal_static_URLRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SearchEngineServerRPC.SearchEngine.URLRequest.class, SearchEngineServerRPC.SearchEngine.URLRequest.Builder.class);
      }

      // Construct using SearchEngineServerRPC.SearchEngine.URLRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        keyword_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SearchEngineServerRPC.SearchEngine.internal_static_URLRequest_descriptor;
      }

      @java.lang.Override
      public SearchEngineServerRPC.SearchEngine.URLRequest getDefaultInstanceForType() {
        return SearchEngineServerRPC.SearchEngine.URLRequest.getDefaultInstance();
      }

      @java.lang.Override
      public SearchEngineServerRPC.SearchEngine.URLRequest build() {
        SearchEngineServerRPC.SearchEngine.URLRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public SearchEngineServerRPC.SearchEngine.URLRequest buildPartial() {
        SearchEngineServerRPC.SearchEngine.URLRequest result = new SearchEngineServerRPC.SearchEngine.URLRequest(this);
        result.keyword_ = keyword_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SearchEngineServerRPC.SearchEngine.URLRequest) {
          return mergeFrom((SearchEngineServerRPC.SearchEngine.URLRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SearchEngineServerRPC.SearchEngine.URLRequest other) {
        if (other == SearchEngineServerRPC.SearchEngine.URLRequest.getDefaultInstance()) return this;
        if (!other.getKeyword().isEmpty()) {
          keyword_ = other.keyword_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SearchEngineServerRPC.SearchEngine.URLRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SearchEngineServerRPC.SearchEngine.URLRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object keyword_ = "";
      /**
       * <code>string Keyword = 1;</code>
       */
      public java.lang.String getKeyword() {
        java.lang.Object ref = keyword_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          keyword_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Keyword = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeywordBytes() {
        java.lang.Object ref = keyword_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          keyword_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Keyword = 1;</code>
       */
      public Builder setKeyword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        keyword_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string Keyword = 1;</code>
       */
      public Builder clearKeyword() {
        
        keyword_ = getDefaultInstance().getKeyword();
        onChanged();
        return this;
      }
      /**
       * <code>string Keyword = 1;</code>
       */
      public Builder setKeywordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        keyword_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:URLRequest)
    }

    // @@protoc_insertion_point(class_scope:URLRequest)
    private static final SearchEngineServerRPC.SearchEngine.URLRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SearchEngineServerRPC.SearchEngine.URLRequest();
    }

    public static SearchEngineServerRPC.SearchEngine.URLRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<URLRequest>
        PARSER = new com.google.protobuf.AbstractParser<URLRequest>() {
      @java.lang.Override
      public URLRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new URLRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<URLRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<URLRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public SearchEngineServerRPC.SearchEngine.URLRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ValidURLOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ValidURL)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool isValid = 1;</code>
     */
    boolean getIsValid();
  }
  /**
   * Protobuf type {@code ValidURL}
   */
  public  static final class ValidURL extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ValidURL)
      ValidURLOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ValidURL.newBuilder() to construct.
    private ValidURL(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ValidURL() {
      isValid_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ValidURL(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              isValid_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SearchEngineServerRPC.SearchEngine.internal_static_ValidURL_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SearchEngineServerRPC.SearchEngine.internal_static_ValidURL_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SearchEngineServerRPC.SearchEngine.ValidURL.class, SearchEngineServerRPC.SearchEngine.ValidURL.Builder.class);
    }

    public static final int ISVALID_FIELD_NUMBER = 1;
    private boolean isValid_;
    /**
     * <code>bool isValid = 1;</code>
     */
    public boolean getIsValid() {
      return isValid_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (isValid_ != false) {
        output.writeBool(1, isValid_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (isValid_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, isValid_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SearchEngineServerRPC.SearchEngine.ValidURL)) {
        return super.equals(obj);
      }
      SearchEngineServerRPC.SearchEngine.ValidURL other = (SearchEngineServerRPC.SearchEngine.ValidURL) obj;

      boolean result = true;
      result = result && (getIsValid()
          == other.getIsValid());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ISVALID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsValid());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SearchEngineServerRPC.SearchEngine.ValidURL parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SearchEngineServerRPC.SearchEngine.ValidURL parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SearchEngineServerRPC.SearchEngine.ValidURL parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SearchEngineServerRPC.SearchEngine.ValidURL parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SearchEngineServerRPC.SearchEngine.ValidURL parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SearchEngineServerRPC.SearchEngine.ValidURL parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SearchEngineServerRPC.SearchEngine.ValidURL parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SearchEngineServerRPC.SearchEngine.ValidURL parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SearchEngineServerRPC.SearchEngine.ValidURL parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SearchEngineServerRPC.SearchEngine.ValidURL parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SearchEngineServerRPC.SearchEngine.ValidURL parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SearchEngineServerRPC.SearchEngine.ValidURL parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SearchEngineServerRPC.SearchEngine.ValidURL prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ValidURL}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ValidURL)
        SearchEngineServerRPC.SearchEngine.ValidURLOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SearchEngineServerRPC.SearchEngine.internal_static_ValidURL_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SearchEngineServerRPC.SearchEngine.internal_static_ValidURL_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SearchEngineServerRPC.SearchEngine.ValidURL.class, SearchEngineServerRPC.SearchEngine.ValidURL.Builder.class);
      }

      // Construct using SearchEngineServerRPC.SearchEngine.ValidURL.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        isValid_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SearchEngineServerRPC.SearchEngine.internal_static_ValidURL_descriptor;
      }

      @java.lang.Override
      public SearchEngineServerRPC.SearchEngine.ValidURL getDefaultInstanceForType() {
        return SearchEngineServerRPC.SearchEngine.ValidURL.getDefaultInstance();
      }

      @java.lang.Override
      public SearchEngineServerRPC.SearchEngine.ValidURL build() {
        SearchEngineServerRPC.SearchEngine.ValidURL result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public SearchEngineServerRPC.SearchEngine.ValidURL buildPartial() {
        SearchEngineServerRPC.SearchEngine.ValidURL result = new SearchEngineServerRPC.SearchEngine.ValidURL(this);
        result.isValid_ = isValid_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SearchEngineServerRPC.SearchEngine.ValidURL) {
          return mergeFrom((SearchEngineServerRPC.SearchEngine.ValidURL)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SearchEngineServerRPC.SearchEngine.ValidURL other) {
        if (other == SearchEngineServerRPC.SearchEngine.ValidURL.getDefaultInstance()) return this;
        if (other.getIsValid() != false) {
          setIsValid(other.getIsValid());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SearchEngineServerRPC.SearchEngine.ValidURL parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SearchEngineServerRPC.SearchEngine.ValidURL) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean isValid_ ;
      /**
       * <code>bool isValid = 1;</code>
       */
      public boolean getIsValid() {
        return isValid_;
      }
      /**
       * <code>bool isValid = 1;</code>
       */
      public Builder setIsValid(boolean value) {
        
        isValid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isValid = 1;</code>
       */
      public Builder clearIsValid() {
        
        isValid_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ValidURL)
    }

    // @@protoc_insertion_point(class_scope:ValidURL)
    private static final SearchEngineServerRPC.SearchEngine.ValidURL DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SearchEngineServerRPC.SearchEngine.ValidURL();
    }

    public static SearchEngineServerRPC.SearchEngine.ValidURL getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ValidURL>
        PARSER = new com.google.protobuf.AbstractParser<ValidURL>() {
      @java.lang.Override
      public ValidURL parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ValidURL(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ValidURL> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ValidURL> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public SearchEngineServerRPC.SearchEngine.ValidURL getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface KeywordRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:KeywordRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string URL = 1;</code>
     */
    java.lang.String getURL();
    /**
     * <code>string URL = 1;</code>
     */
    com.google.protobuf.ByteString
        getURLBytes();
  }
  /**
   * Protobuf type {@code KeywordRequest}
   */
  public  static final class KeywordRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:KeywordRequest)
      KeywordRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use KeywordRequest.newBuilder() to construct.
    private KeywordRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private KeywordRequest() {
      uRL_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private KeywordRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              uRL_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SearchEngineServerRPC.SearchEngine.internal_static_KeywordRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SearchEngineServerRPC.SearchEngine.internal_static_KeywordRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SearchEngineServerRPC.SearchEngine.KeywordRequest.class, SearchEngineServerRPC.SearchEngine.KeywordRequest.Builder.class);
    }

    public static final int URL_FIELD_NUMBER = 1;
    private volatile java.lang.Object uRL_;
    /**
     * <code>string URL = 1;</code>
     */
    public java.lang.String getURL() {
      java.lang.Object ref = uRL_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uRL_ = s;
        return s;
      }
    }
    /**
     * <code>string URL = 1;</code>
     */
    public com.google.protobuf.ByteString
        getURLBytes() {
      java.lang.Object ref = uRL_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uRL_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getURLBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uRL_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getURLBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uRL_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SearchEngineServerRPC.SearchEngine.KeywordRequest)) {
        return super.equals(obj);
      }
      SearchEngineServerRPC.SearchEngine.KeywordRequest other = (SearchEngineServerRPC.SearchEngine.KeywordRequest) obj;

      boolean result = true;
      result = result && getURL()
          .equals(other.getURL());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + URL_FIELD_NUMBER;
      hash = (53 * hash) + getURL().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SearchEngineServerRPC.SearchEngine.KeywordRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SearchEngineServerRPC.SearchEngine.KeywordRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SearchEngineServerRPC.SearchEngine.KeywordRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SearchEngineServerRPC.SearchEngine.KeywordRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SearchEngineServerRPC.SearchEngine.KeywordRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SearchEngineServerRPC.SearchEngine.KeywordRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SearchEngineServerRPC.SearchEngine.KeywordRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SearchEngineServerRPC.SearchEngine.KeywordRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SearchEngineServerRPC.SearchEngine.KeywordRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SearchEngineServerRPC.SearchEngine.KeywordRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SearchEngineServerRPC.SearchEngine.KeywordRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SearchEngineServerRPC.SearchEngine.KeywordRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SearchEngineServerRPC.SearchEngine.KeywordRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code KeywordRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:KeywordRequest)
        SearchEngineServerRPC.SearchEngine.KeywordRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SearchEngineServerRPC.SearchEngine.internal_static_KeywordRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SearchEngineServerRPC.SearchEngine.internal_static_KeywordRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SearchEngineServerRPC.SearchEngine.KeywordRequest.class, SearchEngineServerRPC.SearchEngine.KeywordRequest.Builder.class);
      }

      // Construct using SearchEngineServerRPC.SearchEngine.KeywordRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        uRL_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SearchEngineServerRPC.SearchEngine.internal_static_KeywordRequest_descriptor;
      }

      @java.lang.Override
      public SearchEngineServerRPC.SearchEngine.KeywordRequest getDefaultInstanceForType() {
        return SearchEngineServerRPC.SearchEngine.KeywordRequest.getDefaultInstance();
      }

      @java.lang.Override
      public SearchEngineServerRPC.SearchEngine.KeywordRequest build() {
        SearchEngineServerRPC.SearchEngine.KeywordRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public SearchEngineServerRPC.SearchEngine.KeywordRequest buildPartial() {
        SearchEngineServerRPC.SearchEngine.KeywordRequest result = new SearchEngineServerRPC.SearchEngine.KeywordRequest(this);
        result.uRL_ = uRL_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SearchEngineServerRPC.SearchEngine.KeywordRequest) {
          return mergeFrom((SearchEngineServerRPC.SearchEngine.KeywordRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SearchEngineServerRPC.SearchEngine.KeywordRequest other) {
        if (other == SearchEngineServerRPC.SearchEngine.KeywordRequest.getDefaultInstance()) return this;
        if (!other.getURL().isEmpty()) {
          uRL_ = other.uRL_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SearchEngineServerRPC.SearchEngine.KeywordRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SearchEngineServerRPC.SearchEngine.KeywordRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object uRL_ = "";
      /**
       * <code>string URL = 1;</code>
       */
      public java.lang.String getURL() {
        java.lang.Object ref = uRL_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uRL_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string URL = 1;</code>
       */
      public com.google.protobuf.ByteString
          getURLBytes() {
        java.lang.Object ref = uRL_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uRL_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string URL = 1;</code>
       */
      public Builder setURL(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uRL_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string URL = 1;</code>
       */
      public Builder clearURL() {
        
        uRL_ = getDefaultInstance().getURL();
        onChanged();
        return this;
      }
      /**
       * <code>string URL = 1;</code>
       */
      public Builder setURLBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uRL_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:KeywordRequest)
    }

    // @@protoc_insertion_point(class_scope:KeywordRequest)
    private static final SearchEngineServerRPC.SearchEngine.KeywordRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SearchEngineServerRPC.SearchEngine.KeywordRequest();
    }

    public static SearchEngineServerRPC.SearchEngine.KeywordRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<KeywordRequest>
        PARSER = new com.google.protobuf.AbstractParser<KeywordRequest>() {
      @java.lang.Override
      public KeywordRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new KeywordRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<KeywordRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<KeywordRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public SearchEngineServerRPC.SearchEngine.KeywordRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface URLsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:URLs)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string FoundURL = 1;</code>
     */
    java.lang.String getFoundURL();
    /**
     * <code>string FoundURL = 1;</code>
     */
    com.google.protobuf.ByteString
        getFoundURLBytes();
  }
  /**
   * Protobuf type {@code URLs}
   */
  public  static final class URLs extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:URLs)
      URLsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use URLs.newBuilder() to construct.
    private URLs(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private URLs() {
      foundURL_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private URLs(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              foundURL_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SearchEngineServerRPC.SearchEngine.internal_static_URLs_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SearchEngineServerRPC.SearchEngine.internal_static_URLs_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SearchEngineServerRPC.SearchEngine.URLs.class, SearchEngineServerRPC.SearchEngine.URLs.Builder.class);
    }

    public static final int FOUNDURL_FIELD_NUMBER = 1;
    private volatile java.lang.Object foundURL_;
    /**
     * <code>string FoundURL = 1;</code>
     */
    public java.lang.String getFoundURL() {
      java.lang.Object ref = foundURL_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        foundURL_ = s;
        return s;
      }
    }
    /**
     * <code>string FoundURL = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFoundURLBytes() {
      java.lang.Object ref = foundURL_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        foundURL_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getFoundURLBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, foundURL_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFoundURLBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, foundURL_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SearchEngineServerRPC.SearchEngine.URLs)) {
        return super.equals(obj);
      }
      SearchEngineServerRPC.SearchEngine.URLs other = (SearchEngineServerRPC.SearchEngine.URLs) obj;

      boolean result = true;
      result = result && getFoundURL()
          .equals(other.getFoundURL());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FOUNDURL_FIELD_NUMBER;
      hash = (53 * hash) + getFoundURL().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SearchEngineServerRPC.SearchEngine.URLs parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SearchEngineServerRPC.SearchEngine.URLs parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SearchEngineServerRPC.SearchEngine.URLs parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SearchEngineServerRPC.SearchEngine.URLs parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SearchEngineServerRPC.SearchEngine.URLs parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SearchEngineServerRPC.SearchEngine.URLs parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SearchEngineServerRPC.SearchEngine.URLs parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SearchEngineServerRPC.SearchEngine.URLs parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SearchEngineServerRPC.SearchEngine.URLs parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SearchEngineServerRPC.SearchEngine.URLs parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SearchEngineServerRPC.SearchEngine.URLs parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SearchEngineServerRPC.SearchEngine.URLs parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SearchEngineServerRPC.SearchEngine.URLs prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code URLs}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:URLs)
        SearchEngineServerRPC.SearchEngine.URLsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SearchEngineServerRPC.SearchEngine.internal_static_URLs_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SearchEngineServerRPC.SearchEngine.internal_static_URLs_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SearchEngineServerRPC.SearchEngine.URLs.class, SearchEngineServerRPC.SearchEngine.URLs.Builder.class);
      }

      // Construct using SearchEngineServerRPC.SearchEngine.URLs.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        foundURL_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SearchEngineServerRPC.SearchEngine.internal_static_URLs_descriptor;
      }

      @java.lang.Override
      public SearchEngineServerRPC.SearchEngine.URLs getDefaultInstanceForType() {
        return SearchEngineServerRPC.SearchEngine.URLs.getDefaultInstance();
      }

      @java.lang.Override
      public SearchEngineServerRPC.SearchEngine.URLs build() {
        SearchEngineServerRPC.SearchEngine.URLs result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public SearchEngineServerRPC.SearchEngine.URLs buildPartial() {
        SearchEngineServerRPC.SearchEngine.URLs result = new SearchEngineServerRPC.SearchEngine.URLs(this);
        result.foundURL_ = foundURL_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SearchEngineServerRPC.SearchEngine.URLs) {
          return mergeFrom((SearchEngineServerRPC.SearchEngine.URLs)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SearchEngineServerRPC.SearchEngine.URLs other) {
        if (other == SearchEngineServerRPC.SearchEngine.URLs.getDefaultInstance()) return this;
        if (!other.getFoundURL().isEmpty()) {
          foundURL_ = other.foundURL_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SearchEngineServerRPC.SearchEngine.URLs parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SearchEngineServerRPC.SearchEngine.URLs) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object foundURL_ = "";
      /**
       * <code>string FoundURL = 1;</code>
       */
      public java.lang.String getFoundURL() {
        java.lang.Object ref = foundURL_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          foundURL_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string FoundURL = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFoundURLBytes() {
        java.lang.Object ref = foundURL_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          foundURL_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string FoundURL = 1;</code>
       */
      public Builder setFoundURL(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        foundURL_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string FoundURL = 1;</code>
       */
      public Builder clearFoundURL() {
        
        foundURL_ = getDefaultInstance().getFoundURL();
        onChanged();
        return this;
      }
      /**
       * <code>string FoundURL = 1;</code>
       */
      public Builder setFoundURLBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        foundURL_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:URLs)
    }

    // @@protoc_insertion_point(class_scope:URLs)
    private static final SearchEngineServerRPC.SearchEngine.URLs DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SearchEngineServerRPC.SearchEngine.URLs();
    }

    public static SearchEngineServerRPC.SearchEngine.URLs getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<URLs>
        PARSER = new com.google.protobuf.AbstractParser<URLs>() {
      @java.lang.Override
      public URLs parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new URLs(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<URLs> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<URLs> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public SearchEngineServerRPC.SearchEngine.URLs getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_URLRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_URLRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ValidURL_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ValidURL_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_KeywordRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_KeywordRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_URLs_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_URLs_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022SearchEngine.proto\"\035\n\nURLRequest\022\017\n\007Ke" +
      "yword\030\001 \001(\t\"\033\n\010ValidURL\022\017\n\007isValid\030\001 \001(\010" +
      "\"\035\n\016KeywordRequest\022\013\n\003URL\030\001 \001(\t\"\030\n\004URLs\022" +
      "\020\n\010FoundURL\030\001 \001(\t2a\n\rEngineService\022%\n\013Re" +
      "questSite\022\013.URLRequest\032\t.ValidURL\022)\n\rSea" +
      "rchRequest\022\017.KeywordRequest\032\005.URLs0\001B\027\n\025" +
      "SearchEngineServerRPCb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_URLRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_URLRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_URLRequest_descriptor,
        new java.lang.String[] { "Keyword", });
    internal_static_ValidURL_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ValidURL_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ValidURL_descriptor,
        new java.lang.String[] { "IsValid", });
    internal_static_KeywordRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_KeywordRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_KeywordRequest_descriptor,
        new java.lang.String[] { "URL", });
    internal_static_URLs_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_URLs_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_URLs_descriptor,
        new java.lang.String[] { "FoundURL", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
